#!/usr/bin/env bash
# Bash script for transferring a file from a client to a server using the scp Linux command.
# Parameters:
#   $1: PATH_TO_FILE - Path to the file to be copied to the server.
#   $2: IP - IP address of the server.
#   $3: USERNAME - Username on the server.
#   $4: PATH_TO_SSH_KEY - Path to the SSH private key for user authentication.

# variables
path="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
filename=$(basename "$BASH_SOURCE")
file="$1"
ip="$2"
user="ubuntu"
key="~/.ssh/id_rsa"

if [ $# -eq 2 ]; then
        scp -i "$key" -o StrictHostKeyChecking=no "$path"/"$file" "$user"@"$ip":/home/"$user"/
else
        echo -e "Usage: $filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
